#!/bin/bash

#PBS -N jacobi
#PBS -joe
#PBS -m a
#PBS -q teaching
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:30:00

cd $PBS_O_WORKDIR

for i in `seq 1 20`; do
    ./jacobi --norder 1000 --iterations 20000 >> jacobi_1000.out
done

for i in `seq 1 20`; do
    ./jacobi --norder 2000 --iterations 20000 >> jacobi_2000.out
done

for i in `seq 1 20`; do
    ./jacobi --norder 4000 --iterations 20000 >> jacobi_4000.out
done
